#!/usr/bin/perl -w
# 
# Sucks embedded URLs in the specified file or URI
# TODO: Integrate with ZAP or burpsuite
#
# August 2016
# (c) spinfoo
#
# Usage: URLSUCKER ([-u url] | [-f file]) [-v]
#
#

use strict;
use LWP::Simple;
use Getopt::Long;
use File::Slurp;

my $ARGV;
my @urls;
my $help;
my $url;
my $file;
my $verbose;


GetOptions(
	'help|?' => \$help,
	'u=s' => \$url,
	'f=s' => \$file,
	'v' => \$verbose
);

sub extract {
	my $body= shift;
	my @p= split /\n/, $body;
	my %matches;
	foreach my $line (@p) {
		while ($line =~ /("[-\w\.\/:?=]+"||'[-\w\.\/:?=]+'||\([-\w\.\/:?=]+\))/g) {
			$matches{$1}= $1 if not exists $matches{$1};
		}
	}
	for my $i (keys %matches) {
		if (length($i) > 3) {
			my $u= substr $i, 1, -1;
			if (!($u ~~ @urls)) {
				push @urls, $u;
			}
		}
	}
	undef %matches;
}

sub show() {
	foreach (sort @urls) {
		print $_,"\n";
	}
}

sub check() {
	my @upa= split /\//, $url;
	my $baseurl= $upa[0]."//".$upa[1].$upa[2];
	foreach (sort @urls) {
		if ( /^\/\// ) {
			if (head($upa[0].$_)) { print "[EXTERNAL ABSOLUTE URL] ".$upa[0].$_."\n"; }
		} elsif ( /^http(s)?:\/\// || head($_) ) {
			print "[EXTERNAL ABSOLUTE URL] ".$_."\n";
		} elsif ( /^\// || head($baseurl.$_) ) {
			print "[ABSOLUTE URL] ".$baseurl.$_."\n";
		} elsif ( head($baseurl."/".$_) ) {
			print "[RELATIVE URL] ".$baseurl."/".$_."\n";
		} elsif ($verbose) {
			print "Found string $_\n";
		}
	}
}


if ($help || ($url && $file) || (!$url && !$file)) {
	print "Syntax: $0 ([-u url] | [-f file]) [-v]\n";
} elsif ($url) {
	if (head($url)) {
		extract(get($url));
		check();
	} else {
		print "Could not connect to $url\n";
		exit 1;
	}
} elsif ($file) {
	my $text= read_file($file) or die("Could not read $file");
	extract($text);
	show();
}

exit 0;

